### ISSUE TITLE
How to build a custom OTel receiver

### ISSUE THREAD

**Issue by zmoog** [zmoog/public-notes#106]
I want to learn how to build a custom OpenTelemetry receiver.

**Comment by zmoog** [comment]
Why

- collect data from unsupported sources
- learn how receivers work

**Comment by zmoog** [comment]
Created a GitHub repo using the work at https://zmoog.dev/posts/how-to-build-a-custom-open-telemery-collector/

**Comment by zmoog** [comment]
https://github.com/zmoog/custom-otel-collector

**Comment by zmoog** [comment]
The OTel docs contains a detailed guide about how to build a (traces) receiver: https://opentelemetry.io/docs/collector/building/receiver/ 

Here is my journey.

**Comment by zmoog** [comment]
Overview

- Set up a Go module for the receiver
- Design the config
- Build the factory
- Implement the receiver
- Add the receiver to the collector
- Running and debugging the receiver

**Comment by zmoog** [comment]
I want to focus this note to building and running a working no-op receiver component, leaving all data model design to a dedicated note.

**Comment by zmoog** [comment]
## Set up a Go module for the receiver

In this note, I will scaffold a custom receiver for my solar panel inverter build by ZCS.

```sh
mkdir -p receiver/zcsreceiver
cd receiver/zcsreceiver 

$ go mod init github.com/zmoog/custom-otel-collector/receiver/zcsreceiver 
go: creating new go.mod: module github.com/zmoog/custom-otel-collector/receiver/zcsreceiver

cd ../..

go work use receiver/zcsreceiver 
```

**Comment by zmoog** [comment]
## Design the config

Opening the collector's `config.yaml` file and start writing down the setting your ideal settings is a good starting point:

```yaml
receivers:
  zcs: # this line represents the ID of your receiver
```

### interval

Since the inverter data lives in the ZCS cloud, this receiver will periodically scrape the metrics from the ZCS cloud API.

At the moment we probably need at least an `interval` setting.

```yaml
receivers:
  zcs: # this line represents the ID of your receiver
    interval: 1m
```

### Authentication

The ZCS API requires authentication, so we probably need to also add dedicated options:

```yaml
receivers:
  zcs: # this line represents the ID of your receiver
    interval: 1m
    auth:
      client_id: ${env:ZCS_CLIENT_ID}
      auth_key: ${env:ZCS_AUTH_KEY}
```

### Filter

Finally, users may have one or more inverters, so we need to include an option to list the inverter serial numbers thay want to collect data from:

```yaml
receivers:
  zcs: # this line represents the ID of your receiver
    interval: 1m
    auth:
      client_id: ${env:ZCS_CLIENT_ID}
      auth_key: ${env:ZCS_AUTH_KEY}
    thing_ids:
      - ${env:ZCS_THING_KEY}
```
