### ISSUE TITLE
Figure out how to run Filebeat in debug mode using GoLand

### ISSUE THREAD

**Issue by zmoog** [zmoog/public-notes#28]
Suppose you want to run Filebeat in debug mode to explore in detail how Filebeat executes some portion of the code.

**Comment by zmoog** [comment]
Open the `main.go` file at `x-pack/filebeat/main.go` and "Modify Run Configuration:

<img width="958" alt="CleanShot 2023-03-31 at 15 34 06@2x" src="https://user-images.githubusercontent.com/25941/229134422-4e696ae0-1871-4988-bc05-5c5a03683acc.png">

In Program Argument, set the following content:

```
-e
-v
-d
*
--strict.perms=false
--path.home
/Users/zmoog/code/projects/elastic/beats/x-pack/metricbeat
-E
cloud.id=REDACTED
-E
cloud.auth=REDACTED
-E
gc_percent=100
-E
setup.ilm.enabled=false
-E
setup.template.enabled=false
-E
output.elasticsearch.allow_older_versions=true
```

Set `cloud.id` and `cloud.auth` with your actual values to access your Elasticsearch cluster.

**Comment by zmoog** [comment]
Enable one module; we have something to prove this is working.

```shell
# open a terminal at the project root and cd into filebeat
$ cd x-pack/filebeat/ 

# enable the azure module
$ cp modules.d/azure.yml.disabled modules.d/azure.yml 
```

Edit `modules.d/azure.yml` and enable at least one input. 

For example, for this test I am enabling the sign in logs:

```yaml
  signinlogs:
    enabled: true
    var:
      eventhub: REDACTED
      consumer_group: "$Default"
      connection_string: REDACTED
      storage_account: REDACTED
      storage_account_key: REDACTED
```
