### ISSUE TITLE
Figure out how to route documents to a different data stream in Elasticsearch

### ISSUE THREAD

**Issue by zmoog** [zmoog/public-notes#42]

**Comment by zmoog** [comment]
Basic example of a pipeline that routes document based on Kubernetes labels:

```yaml
---
description: Pipeline for Kubernetes container logs
processors:
  - reroute:
      dataset:
        - '{{kubernetes.labels.elastic_co/dataset}}'
        - '{{data_stream.dataset}}'
      namespace:
        - '{{kubernetes.labels.elastic_co/namespace}}'
        - '{{data_stream.namespace}}'
```

The `dataset` and `namespace` can be a single value or and array. It will use the first valid value in the list.
