### ISSUE TITLE
Figure out how to collect ECS/ContainerInsights metrics using the CloudWatch metrics integration

### ISSUE THREAD

**Issue by zmoog** [zmoog/public-notes#43]
The basic ECS metrics do not have information about ECS tasks. Let's try with the ECS/ContainerInsights metrics.

**Comment by zmoog** [comment]
Install the AWS CloudWatch integration and enable the "Collect metrics from CloudWatch" integration:

![CleanShot 2023-07-27 at 10 36 07@2x](https://github.com/zmoog/public-notes/assets/25941/39620ac1-9ada-44f3-a879-a3f9aaf68106)

Quick run with the default configuration to make sure authentication is set up correctly and we're getting data:

![CleanShot 2023-07-27 at 10 41 29@2x](https://github.com/zmoog/public-notes/assets/25941/5b78a2b1-b990-461f-9311-a1905891f376)

**Comment by zmoog** [comment]
The next step is to visit CloudWatch on the AWS console and check Metrics > All Metrics section to check which metrics have values:

![CleanShot 2023-07-27 at 10 44 36@2x](https://github.com/zmoog/public-notes/assets/25941/94c3e76a-f089-4840-b0b0-a4904bd9fffd)

**Comment by zmoog** [comment]
## Metric docs

AWS has a nice page about [Metrics collected by Container Insights](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-metrics.html) that covers both ECS and EKS. For ECS, we can use the [Amazon ECS Container Insights metrics](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-metrics-ECS.html) page.
 
## Configuration

With this information, I would start changing the default configuration file and replace EC2 metrics with some ECS/Container Insights metrics:

```yaml
- namespace: ECS/ContainerInsights
  resource_type: ecs
  name:
    - CpuUtilized
    - CpuReserved
  statistic:
    - Average
    - Maximum
  # dimensions:
  #  - name: InstanceId
  #     value: i-123456
  # tags:
  #   - key: created-by
  #     value: foo

```
