### ISSUE TITLE
Figure out how to set up ESF to use `ssl_assert_fingerprint` option with Elasticsearch

### ISSUE THREAD

**Issue by zmoog** [zmoog/public-notes#45]
In v1.5.0, the pull request https://github.com/elastic/elastic-serverless-forwarder/pull/173 introduces the SSL fingerprint option to access Elasticsearch clusters using self-signed certificates.

I want to test it and add step-by-step instructions on how to set it up.

**Comment by zmoog** [comment]
To set the `ssl_assert_fingerprint` option, you must edit the config file stored in the S3 bucket.

Suppose you have a `config.yml` file stored in the bucket with the following content:

```yaml
inputs:
  - type: "s3-sqs"
    id: "arn:aws:sqs:eu-west-1:<REDACTED>:zmoog-dev-access-logs"
    outputs:
      - type: "elasticsearch"
        args:
          api_key: "<REDACTED>"
          es_datastream_name: "logs-aws.s3access-default"
          batch_max_actions: 500
          batch_max_bytes: 10485760
          ssl_assert_fingerprint: ""
```

In this example, the `ssl_assert_fingerprint` is blank, the default option. With this value, the `ssl_assert_fingerprint` is ignored, and ESF will validate the HTTPS certificate.

**Comment by zmoog** [comment]
The next step is to get the fingerprint of the HTTPS certificate your Elasticsearch cluster is using now.

You can use OpenSSL to get the fingerprint for your certificate. Here's an example using an Elasticsearch cluster hosted on Elastic Cloud:

```shell
$ openssl s_client \
    -connect my-deployment.es.eastus2.azure.elastic-cloud.com:443 \
    -showcerts </dev/null 2>/dev/null | openssl x509 -noout -fingerprint

SHA1 Fingerprint=1C:46:32:75:AA:D6:F1:E2:8E:10:A3:64:44:B1:36:C9:7D:44:35:B4
```

You can use your DNS name, IP address, and port number instead of `my-deployment.es.eastus2.azure.elastic-cloud.com:443` from the above example.

Copy your fingerprint value for the next step.

**Comment by zmoog** [comment]
As a final step, edit your `config.yml` file to use the SSL fingerprint:

```yaml
inputs:
  - type: "s3-sqs"
    id: "arn:aws:sqs:eu-west-1:<REDACTED>:zmoog-dev-access-logs"
    outputs:
      - type: "elasticsearch"
        args:
          api_key: "<REDACTED>"
          es_datastream_name: "logs-aws.s3access-default"
          batch_max_actions: 500
          batch_max_bytes: 10485760
          ssl_assert_fingerprint: "1C:46:32:75:AA:D6:F1:E2:8E:10:A3:64:44:B1:36:C9:7D:44:35:B4"
```
