### ISSUE TITLE
Figure out the permissions required to run the GCP Billing integration

### ISSUE THREAD

**Issue by zmoog** [zmoog/public-notes#56]
I want to update the [GCP Billing Metrics integration docs page](https://docs.elastic.co/integrations/gcp/billing) with a details about permissions.

My plan is to set up a service account with no permissions and add one at a time.

**Comment by zmoog** [comment]
## Create a Service Account

- Visit **IAM & Admin > Service Accounts**
- Click on **Create Service Account**
- Set "mbranca-billing-metrics" as **Service account name**
- Click on **Create and continue**
- Click on **Done**

I don't want to assign any role for now.

**Comment by zmoog** [comment]
## Set up GCP configuration file

I am going to use Metricbeat in debug mode. I enable the GCP module with the following configuration:

```yaml
- module: gcp
  metricsets:
    - billing
  period: 24h
  project_id: <my project id>
  credentials_json: <my credentials json string>
  dataset_id: "billing_testing"
  table_pattern: "gcp_billing_export_v1"
  cost_type: "regular"
```

Optional, but nice. Format the credentials JSON string with `jq` before setting it in the `credentials_json` configuration option:

```shell
cat ~/Downloads/<project>-f4bf474898e4.json | jq -c
```
