### ISSUE TITLE
Figure out how the Filebeat registry stores entries

### ISSUE THREAD

**Issue by zmoog** [zmoog/public-notes#57]
I am investigating a user problem with Filebeat re-processing the same S3 objects file after a restart.

I suspect this may happen because it didn't track properly the state for each S3 object, so I want to learn how and where the registry stores its content.

**Comment by zmoog** [comment]
On a 8.8.2 cluster, I set up an agent to collect CloudTrail logs from an S3 bucket. The `aws-s3` is configured for polling the bucket.

Here's the agent policy:

```yaml
  - id: aws-s3-cloudtrail-a10aca5c-590b-4643-ad4e-48c6fb65ddbf
    name: aws-14
    revision: 3
    type: aws-s3
    use_output: default
    meta:
      package:
        name: aws
        version: 1.51.1
    data_stream:
      namespace: default
    package_policy_id: a10aca5c-590b-4643-ad4e-48c6fb65ddbf
    streams:
      - id: aws-s3-aws.cloudtrail-a10aca5c-590b-4643-ad4e-48c6fb65ddbf
        data_stream:
          dataset: aws.cloudtrail
          type: logs
        file_selectors:
          - regex: /CloudTrail/
            expand_event_list_from_field: Records
          - regex: /CloudTrail-Digest/
          - regex: /CloudTrail-Insight/
            expand_event_list_from_field: Records
        access_key_id: <REDACTED>
        content_type: application/json
        expand_event_list_from_field: Records
        secret_access_key: <REDACTED>
        max_number_of_messages: 5
        tags:
          - forwarded
          - aws-cloudtrail
        publisher_pipeline.disable_host: true
```
