### ISSUE TITLE
How to use multiple modules at the same time

### ISSUE THREAD

**Issue by zmoog** [zmoog/public-notes#6]
I want to collect activity logs from two event hubs using the same Filebeat. I want to use the Azure module.

Is it possible, and how to achieve it?

**Comment by zmoog** [comment]
I guess we need to define multiple modules, for example:

```yaml
# Module: azure
# Docs: https://www.elastic.co/guide/en/beats/filebeat/main/filebeat-module-azure.html

- module: azure
  signinlogs:
    enabled: true
    var:
      eventhub: ".."
      consumer_group: ".."
      connection_string: ".."
      storage_account: ".."
      storage_account_key: ".."

- module: azure
  signinlogs:
    enabled: true
    var:
      eventhub: ""
      consumer_group: ""
      connection_string: ""
      storage_account: ""
      storage_account_key: ""

```

I ran a quick test, and with this configuration, I can spot two `azure-eventhub` inputs starting in the logs.
