### ISSUE TITLE
Figure out how to collect any metric using the Azure Monitor integration

### ISSUE THREAD

**Issue by zmoog** [zmoog/public-notes#69]

**Comment by zmoog** [comment]
## Create test resources

I am creating a new PostgreSQL Flexible server to collect metrics from:

![CleanShot 2024-01-25 at 11 57 26@2x](https://github.com/zmoog/public-notes/assets/25941/21a24eae-09df-46af-b5a6-593933988041)

I selected the "Development" workload type, I think it will be okay for this purpose.

**Comment by zmoog** [comment]
## PostgreSQL Flexible server metrics in Azure Portal

With a new PostgreSQL Flexible server up and running, we can start taking a look at the metrics on the Azure Portal.

For example, here are the value for the **Active Connections** mertric:

![CleanShot 2024-01-25 at 14 47 03@2x](https://github.com/zmoog/public-notes/assets/25941/3421bace-16b7-4df9-8f9f-c90512a09a71)

### Documentation

Here are a few resources about metrics for the PostgreSQL Flexible server service:

- [Monitor metrics on Azure Database for PostgreSQL - Flexible Server](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-monitoring)
- [Supported metrics for Microsoft.DBforPostgreSQL/flexibleServers](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-metrics/microsoft-dbforpostgresql-flexibleservers-metrics)

**Comment by zmoog** [comment]
## N/A

We have a PostgreSQL Flexible server instance, now the next step is open the metric reference for the PostgreSQL Flexible server service an look for interesting metrics.

The [Supported metrics for Microsoft.DBforPostgreSQL/flexibleServers](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-metrics/microsoft-dbforpostgresql-flexibleservers-metrics) contains a list with all the supported metrics.

**Comment by zmoog** [comment]
## Write the configuration

Here's the sample config from the generic Azure Monitor integration:

```yaml
- resource_query: "resourceType eq 'Microsoft.DocumentDb/databaseAccounts'"
  metrics:
  - name: ["DataUsage", "DocumentCount", "DocumentQuota"]
    namespace: "Microsoft.DocumentDb/databaseAccounts"
```

We can use it as a starting point.

Using the information at [Supported metrics for Microsoft.DBforPostgreSQL/flexibleServers](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-metrics/microsoft-dbforpostgresql-flexibleservers-metrics), we can rewrite the configuration for the PostgreSQL Flexible server metrics:

```yaml
- resource_query: "resourceType eq 'Microsoft.DBforPostgreSQL/flexibleServers'"
  metrics:
  - name: 
    - "active_connections"
    namespace: "Microsoft.DBforPostgreSQL/flexibleServers"
```

**Comment by zmoog** [comment]
## Test run

- Create an agent policy
- Add the generic Azure Monitor integration
- Assign the policy to an agent
- Explore the documents

### Create an agent policy

Let's create a brand new agent policy for this test:

![CleanShot 2024-01-26 at 00 05 43@2x](https://github.com/zmoog/public-notes/assets/25941/370ded67-f467-42c2-b348-e4bf2f56726c)

### Add the generic Azure Monitor integration

![CleanShot 2024-01-26 at 00 03 32@2x](https://github.com/zmoog/public-notes/assets/25941/2e731788-b31a-4bb7-8fe7-f5e8c867c702)


### Assign the policy to an agent

Pick an existing agent or install a new one, and assign the "Azure Metrics (PostgreSQL Flexible server)" policy to it.

### Explore the documents

After a couple of minutes, we can see new documents with the "Active Connections" metrics show up:

![CleanShot 2024-01-26 at 00 07 32@2x](https://github.com/zmoog/public-notes/assets/25941/1901ebb2-c755-4ee2-a95b-bf3315d850d3)

**Comment by zmoog** [comment]
## Add extra metrics

Using the same list of [Supported metrics for Microsoft.DBforPostgreSQL/flexibleServers](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-metrics/microsoft-dbforpostgresql-flexibleservers-metrics), we can add more metrics to the configuration:

```yaml
- resource_query: "resourceType eq 'Microsoft.DBforPostgreSQL/flexibleServers'"
  metrics:
  - name: 
    - "active_connections"
    - "memory_percent"
    - "cpu_credits_consumed"
    - "cpu_credits_remaining"
    namespace: "Microsoft.DBforPostgreSQL/flexibleServers"
```

**Comment by zmoog** [comment]
## Add extra metrics with dimensions

Up until now, we added new metrics without specifying any dimension. Let's try adding another metric definition that includes a dimension.

```yaml
- resource_query: "resourceType eq 'Microsoft.DBforPostgreSQL/flexibleServers'"
  metrics:
  - name: 
    - "active_connections"
    - "memory_percent"
    - "storage_free"
    namespace: "Microsoft.DBforPostgreSQL/flexibleServers"
  - name: 
    - "numbackends"
    dimensions:
    -  "DatabaseName"
    namespace: "Microsoft.DBforPostgreSQL/flexibleServers"
```
