### ISSUE TITLE
How to test ingest pipeline in Beats

### ISSUE THREAD

**Issue by zmoog** [zmoog/public-notes#7]

**Comment by zmoog** [comment]
I am using Filebeat as an example.

First, walk into the Filebeat root directory:

```shell
cd x-pack/filebeat/
```

In general you can use the following command:

```shell
TESTING_FILEBEAT_MODULES=<module> \
TESTING_FILEBEAT_FILESETS=<fileset> \
MODULES_PATH=module \
mage -v pythonIntegTest
```

For example, here's the command line to test the `activitylogs` fileset in the `azure` module:

```shell
TESTING_FILEBEAT_MODULES=azure \
TESTING_FILEBEAT_FILESETS=activitylogs \
MODULES_PATH=module \
mage -v pythonIntegTest

```

Additional environment variables:

```shell
# To rebuild the expected logs.
GENERATE=1

# To skip everything but the modules test.
PYTEST_ADDOPTS="-k test_modules"
PYTEST_ADDOPTS="-k test_modules -vv"
```

**Comment by zmoog** [comment]
Here's how to generate the expected files for the pipeline:

```shell
TESTING_FILEBEAT_MODULES=azure \
TESTING_FILEBEAT_FILESETS=activitylogs \
MODULES_PATH=module \
PYTEST_ADDOPTS="-k test_modules -vv" \
GENERATE=1 \
mage -v pythonIntegTest
```

**Comment by zmoog** [comment]
## Stack version

If you want to use a different version of the stack in you tests, you can then update the `testing/environments/snapshot.yml` file:

```yaml
# This should start the environment with the latest snapshots.

version: '2.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0-61c35791-SNAPSHOT
```
