### ISSUE TITLE
Figure out how to run Filebeat on Docker

### ISSUE THREAD

**Issue by zmoog** [zmoog/public-notes#73]
I want to run Filebeat 8.11.3 with a custom configuration on Docker for testing purpose.

Requirements:

- Access configuration files `filebeat.yml` and `3-input.yml` using volume.
- Write events to the file output.

**Comment by zmoog** [comment]
Using https://www.elastic.co/guide/en/beats/filebeat/8.11/running-on-docker.html as source material.

**Comment by zmoog** [comment]
## Pull the image

```shell
docker pull docker.elastic.co/beats/filebeat:8.11.3
```

**Comment by zmoog** [comment]
## Configure Filebeat

```yaml
# filebeat.yml
# ================================== General ====================================
fields_under_root: true
fields:
  service:
    environment: ${ENVIRONMENT}
    app: ${APP_NAME}
    prefix: ${SERVICE_PREFIX}
    name: ${SERVICE_PREFIX}-${ENVIRONMENT}-${APP_NAME}
# ============================== Inputs ===============================
filebeat:
  shutdown_timeout: ${SHUTDOWN_TIMEOUT:30}s
  config.inputs:
    enabled: true
    path: "s3-input.yml"
output.file:
  path: "/tmp/filebeat/"
  filename: filebeat
  rotate_every_kb: 10000
  number_of_files: 7
# ================================== Logging ===================================
logging:
  level: ${LOG_LEVEL:info}
  metrics:
    enabled: false
  to_files: true
  files:
    path: /tmp/filebeat/log/filebeat
    interval: 86400
    rotateeverybytes: 31457280
    keepfiles: 7
    permissions: 0644
    rotateonstartup: false

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
      #  - add_cloud_metadata: ~
      #  - add_docker_metadata: ~
```

```yaml
# s3-input.yml
- type: aws-s3
  enabled: true
  queue_url: "${SQS_QUEUE_URL}"
  credential_profile_name: "elastic"
  api_timeout: 30s
  visibility_timeout: 10s
  sqs.max_receive_count: -1
  sqs.wait_time: 20s
  fields:
    service:
      log_type: "apigw-access"
  fields_under_root: true

```
