### ISSUE TITLE
Figure out how to performance test the aws-s3 input in polling mode

### ISSUE THREAD

**Issue by zmoog** [zmoog/public-notes#77]

**Comment by zmoog** [comment]
## Run 1

In the first run:
- Started the Agent
- Waited for ~30 minutes
- Changed the config to trigger an Agent restart

The goal was to evaluate the impact of interrupting the processing and resuming from the start.

I saved the list of the existing objects in the bucket in the `s3_objects_list-2.csv` file. Here's the number of objects for 2024:

```shell
$ cat s3_objects_list-2.csv | grep '/2024/' | wc -l
  301254
```

**Comment by zmoog** [comment]
## Run 2

The process:

started: 22:00
completed: 02:30

No Agent restarts.

![CleanShot 2024-02-12 at 11 04 44@2x](https://github.com/zmoog/public-notes/assets/25941/a64d31c7-66a9-4497-8dac-eec448b99f4e)

**Comment by zmoog** [comment]
Run 2 details

![CleanShot 2024-02-12 at 11 12 56@2x](https://github.com/zmoog/public-notes/assets/25941/d074e198-5f18-4639-abef-35ae66eaa967)

**Comment by zmoog** [comment]
## Run 3

### Input

```yaml
  - id: aws-s3-cloudtrail-fb93f962-4474-4f15-9032-0473c01ae54b
    name: aws-21
    revision: 14
    type: aws-s3
    use_output: 6a7e2784-665c-4208-afac-380bac62351e
    meta:
      package:
        name: aws
        version: 2.8.5
    data_stream:
      namespace: sdh3988.4
    package_policy_id: fb93f962-4474-4f15-9032-0473c01ae54b
    streams:
      - id: aws-s3-aws.cloudtrail-fb93f962-4474-4f15-9032-0473c01ae54b
        data_stream:
          dataset: aws.cloudtrail
          type: logs
        bucket_arn: '<REDACTED>'
        number_of_workers: 100
        bucket_list_interval: 1m
        file_selectors:
          - regex: /CloudTrail/
            expand_event_list_from_field: Records
          - regex: /CloudTrail-Digest/
          - regex: /CloudTrail-Insight/
            expand_event_list_from_field: Records
        expand_event_list_from_field: Records
        content_type: application/json
        tags:
          - forwarded
          - aws-cloudtrail
        publisher_pipeline.disable_host: true
```

### Output

Preset: Throughput
